// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuQ2t2ngRMKQ3iOsCny-y3SmZhFD0wdKE',
    appId: '1:982867337861:web:7ccf5d7269a904f0157fec',
    messagingSenderId: '982867337861',
    projectId: 'irescue-2e6ca',
    authDomain: 'irescue-2e6ca.firebaseapp.com',
    storageBucket: 'irescue-2e6ca.appspot.com',
    measurementId: 'G-ZPVNMC9RBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFNR4PRQEkzFSyA3hjYWR-sXHPkWylwEY',
    appId: '1:982867337861:android:e195382de95117ea157fec',
    messagingSenderId: '982867337861',
    projectId: 'irescue-2e6ca',
    storageBucket: 'irescue-2e6ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44I74RDbA8CYUxRu8Z3IerihEv4l8r6c',
    appId: '1:982867337861:ios:b0ce6eb24ac9de74157fec',
    messagingSenderId: '982867337861',
    projectId: 'irescue-2e6ca',
    storageBucket: 'irescue-2e6ca.appspot.com',
    iosBundleId: 'com.example.irescue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC44I74RDbA8CYUxRu8Z3IerihEv4l8r6c',
    appId: '1:982867337861:ios:48cb643b80018b3c157fec',
    messagingSenderId: '982867337861',
    projectId: 'irescue-2e6ca',
    storageBucket: 'irescue-2e6ca.appspot.com',
    iosBundleId: 'com.example.irescue.RunnerTests',
  );
}
